"""add name fields

Revision ID: 2ea977fcc981
Revises: 4c2ae3e4fe00
Create Date: 2025-01-29 22:50:02.486867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea977fcc981'
down_revision = '4c2ae3e4fe00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sname', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('sname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
